### ISSUE TITLE
Migrate Heimdall

### ISSUE THREAD

**Issue by sthompson22** [thesis/valkyrie#129]
### What Are We Doing

`cfc-production-deprecated` is now...deprecated.  As a result we've been migrating deployments from `cpd` to Google projects more fitting for the deployment at hand.  In Heimdalls case we'll probably use `thesis-ops`.

Here we breakdown all the bits needed to migrate.

#### Kube

Outside of secrets, Kube config files can be applied as-is to the new cluster.  Need to be on `thesis-ops` VPN and have Kube context set to `thesis-ops`

`heimdall-hubot-deployment` - Deployment
`heimdall-redis-set` - Stateful Set
`heimdall-http-service` - NodePort
`heimdall-redis-service` - ClusterIP
`heimdall-web-ingress` - Ingress
` heimdall-data-heimdall-redis-set-0` - Persistent Volume Claim
`heimdall-hubot` - Secret
##### Secrets
circle_ci_token 
flowdock_token  
github_client_id  
github_client_secret  
google_client_id  
google_client_secret  
heimdall_alert_flow 
host  
imgflip_api_password  
imgflip_api_username  
zoom_api_key  
zoom_api_secret 

#### Webhooks

- Inventory them!

### File / Directory structure

How do we want to name files / organize directories for heimdall components?

Should live under: `heimdall/infrastructure/kube/thesis-ops`

### Open Questions

- How do we migrate secrets?

- How do we migrate data from `heimdall-redis-set` persistent volume?

- Check if Kristen has access to `thesis-ops` / get OpenVPN account

### Migration Steps (subject to change, rough outline off the top)
- [x] Decide on file/directory structure (update: implemented in PR #131 )
- [x] Decide on renaming any of the Kube components (update: implemented in PR #143 )
- [x] Research migrating secrets inter-cluster (issue #147)
- [x] Reserch migrating PV data inter-cluster (for redis-brain) (issue #148)
- [X] Migrate secrets (issue #149)
- [X] Setup persistent volume claim (via kube config) (issue #150)
- [X] Migrate persistent volume data (for redis-brain) (issue #150)
- [X] Deploy redis-brain service and stateful set (issue #150)
- [X] Check data sanity (waves hands) (issue #150)
- [X] Migrate Heimdall image management (issue #161)
- [X] Deploy heimdall Deployment (issue #151)
- [X] Test (waves hands) (issue #151)
- [X] Shut down old heimdall  (issue #151)
- [X] Document All The Things (issue #169)
